### ISSUE TITLE
Als gamedesigners willen we veschillende mini games, zodat de gebruikers leren over password security

### ISSUE THREAD

**Issue by hiddegrei** [hiddegrei/hzproject#12]
Een minigame kan van alles zijn. 

Een vraag over passwords met verschillende antwoorden als opties. Als gebruiker moet je het goede antwoord slepen, waardoor je punten/hints krijgt

**Comment by Jessevdbos** [comment]
Mini-game idee: plaatjes van vingerafdrukken over een sensor houden zodat deze de vingerafdruk controleert en de speler de kluis kan openen

Wachtwoord methode: vingerafdrukken

**Comment by Jessevdbos** [comment]
Mini-game idee: cijfercombinatie kraken door brute-force, om het spel makkelijker te maken zal het juiste cijfer worden gehighlight door een muziektoon of een andere manier waarop het goede antwoord zichtbaar wordt
