### ISSUE TITLE
Als basisshool leerling wil ik een duidelijk verhaallijn, zodat ik weet waarvoor ik het spelletje speel

### ISSUE THREAD

**Issue by hiddegrei** [hiddegrei/hzproject#19]

**Comment by Jessevdbos** [comment]
Verhaallijn:
Je bent een overvaller die gaat proberen de kluis van de bank te kraken. Je maakt een gebruikersnaam en wachtwoord aan op schurknet.com en plaats hier al de details van je overval. Op het moment dat je de bank inloopt (het spel start) begin de overheid met het hacken van je account (je tijd begint te lopen) op schurknet om de details van je overval te vinden. Het is een race tegen de klok om de sleutels van agenten te pakken en de verschillende kamers binnen te komen.

In de kamers tref je verschillende dingen aan, de ene keer een clue de andere keer een kluis. Om de kluis te openen speel je een minigame. Als deze minigame is gewonnen ontvang je een beloning. Dit kan een clue of score zijn. Naarmate je meer clue's verzamelt zal je progressie stijgen. Als je genoeg clue's hebt kun je in de CENTER HALL de boss-minigame spelen. Als deze mini-game is voltooid ben je ontsnapt en kan de politie je niet meer pakken.

**Comment by brentjc** [comment]
Startpagina info van game:

Je bent een bank aan het overvallen door met een speciaal wachtwoord en gebruikersnaam te gebruiken om in de kluis te komen. Maar de politie heeft een manier gevonden om jouw gegevens te ontcijferen. Ze kunnen er lang of kort aan doen om jouw wachtwoord te ontcijferen. Je moet er dus voor zorgen dat je een sterk wachtwoord hebt om meer tijd over te hebben om de bank te overvallen.
