### ISSUE TITLE
als programmeur wil ik dat agenten een bepaalde moeilijkheidsgraad hebben voor het hacken van de agenten

### ISSUE THREAD

**Issue by hiddegrei** [hiddegrei/hzproject#23]

**Comment by Jessevdbos** [comment]
Agenten idee: 
1. agenten met en blauw gezichtsveld zijn onwetend, als deze agenten jou ontdekken word het gezichtsveld groen.
2. agenten met een groen gezichtsveld zijn zogenaamde 'heat-seakers' zij zijn actief op zoek naar de speler, als deze agenten jou ontdekken ben je af.

* agenten met de kleur geel zijn EASY-MODE agenten, deze agenten hebben een single defence
* agenten met de kleur oranje zijn NORMAL-MODE agenten, deze agenten hebben een double defence
* agenten met de kleur rood zijn HARD-MODE agenten, deze agenten hebben een triple defence
