### ISSUE TITLE
als Basisschool scholier wil ik graag een leuke map, zodat ik een het spel leuker vindt om te spelen

### ISSUE THREAD

**Issue by Jessevdbos** [hiddegrei/hzproject#3]
Maak een leuke map zodat scholieren het spel aantrekkelijker vinden, hierdoor gaan ze het spel vaker spelen en de keren dat ze spelen zullen ze het spel interessanter vinden dan als er geen leuke map voor de scholieren wordt gemaakt.

1 van de scholieren gaf aan dat ze het gebruik van de map van cluedo een enorme + vond. Dit kunnen we gebruiken in het overleg over de layout van de map

**Comment by hiddegrei** [comment]
Een level definieer ik als een array van arrays.
Elk element in het array is een array van 4 elementen.
Deze 4 elementen zijn,: de x-coordinaat van het 1e punt van de border, de y-coordinaat van het 1e punt van de border.
En de x en y coordinaat van het 2e punt van de border.

**Comment by Jessevdbos** [comment]
Map moet op een bank lijken om aan het thema van het spel te voldoen

**Comment by hiddegrei** [comment]
eisen:

1. centrale hub
2. shop
3. plekken op de map waar punten zijn te halen( vragen stellen bv)
