### ISSUE TITLE
Als basisschool scholier wil ik graag meer uitdaging op de map, hierdoor kan ik meer worden uitgedaagd en ben ik niet te snel klaar met het spel

### ISSUE THREAD

**Issue by Jessevdbos** [hiddegrei/hzproject#4]
Bewegende agenten

**Comment by Jessevdbos** [comment]
Een manier om het lopen makkelijker te maken (geheime gangen) of moeilijker (dobbelsteen om het aantal stappen te bepalen)

**Comment by hiddegrei** [comment]
Robots die uit zich zelf door de map lopen, deze moet je als user dus ontwijken

**Comment by hiddegrei** [comment]
Meerdere verschillende maps (levels of verschillende kamers)

**Comment by Jessevdbos** [comment]
Powerups of ingame items waar spelers score aan kunnen besteden om het lvl makelijker te halen (cookie)

**Comment by hiddegrei** [comment]
pacman ghosts strategie

**Comment by Jessevdbos** [comment]
Camera's in verschillende hoeken of gangen die heen en weer bewegen op 1 plek. De camera's zijn uit te schakelen in een aparte kamer voor een bepaalde tijd
