### ISSUE TITLE
als basisschool scholier wil ik graag dat deze game single- en multiplayer is, zodat ik met mijn vrienden kan spelen

### ISSUE THREAD

**Issue by Jessevdbos** [hiddegrei/hzproject#5]
Dit is een moeilijke.

We kunnen WASD en pijltjestoetsen gebruiken voor het toevoegen van 2 spelers, om dit te doen moeten we wel een manier verzinnen om de spelers hun gezichtsveld te bepalen

**Comment by hiddegrei** [comment]
> Dit is een moeilijke.
> 
> We kunnen WASD en pijltjestoetsen gebruiken voor het toevoegen van 2 spelers, om dit te doen moeten we wel een manier verzinnen om de spelers hun gezichtsveld te bepalen

>Dit kan bijvoorbeeld door de map static te maken, de map is de breedte en hoogte van het scherm. En het gezichtsveld wordt bepaald door de positie en richting van de speler

**Comment by hiddegrei** [comment]
in single player mode kan je de muis gebruiken voor movement ( bewegen met de muis is veel soepeler).
In multiplayer kunnen we overschakelen op pijltjes toetsen en WASD

**Comment by hiddegrei** [comment]
online mode via live listeners database
