### ISSUE TITLE
Als programmeur wil ik een class die de scores bijhoudt. Op deze manier kan ik een highscore aan het eind bepalen en kunnen spelers transacties in game maken

### ISSUE THREAD

**Issue by Jessevdbos** [hiddegrei/hzproject#6]
Transacties voor powerups kunnen betaald worden met score

highscore bijhouden moet nog een manier voor worden verzonnen om een database bij te houden

**Comment by hiddegrei** [comment]
als de game over, word de highscore naar een database gestuurd ( firebase)

**Comment by Jessevdbos** [comment]
Score toegevoegd. Nog niet geimplementeerd voor multiplayer of het behalen van score door het winnen van minigames
