### ISSUE TITLE
Als programmeur wil ik een startscreen, zodat ik een gebruikersnaam en wachtwoord kan vragen

### ISSUE THREAD

**Issue by Jessevdbos** [hiddegrei/hzproject#8]
Startscreen wordt gebruikt om de user te ontvangen, hierkan hij/zij nog even wachten tot hij echt het spel wilt beginnen

een gebruikersnaam kan worden opgegeven om het spel persoonlijker te maken voor de user en om een highscore toe te voegen

een wachtwoord kan worden aangemaakt om een timer te zetten voor de speler om in het spel een timelimit te hebben

tijdslimiet kan worden uitgelegd op de startpagina, maar wel hidden zodat niet alle spelers dit zien maar alleen de oplettende speler

**Comment by hiddegrei** [comment]
layout:

Titel 

input veld 1: naam,
input veld 2: wachtwoord,
